name: ecoleta
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  http: ^0.13.1
  font_awesome_flutter: ^9.0.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  mobx_codegen: ^2.0.1+3
  build_runner: ^2.0.4
  flutter_map: ^0.13.1
  flutter_svg: ^0.22.0
  flutter_map_marker_popup: ^1.0.0+1
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true
